task: classify
mode: train
model: yolo11s-cls.pt
data: C:\Users\floot\Florian's Laptop\ESILV\CV and Deep Learning\ESILV_A5_Computer_Vision\dataset_creation\datasets\label_studio_export_cls_dataset_augmented\rank_dataset
imgsz: 224
epochs: 100
batch: 16
device: 0
seed: 42
workers: 4
patience: 20
project: trainning/cls_training_runs
name: rank_dataset
save: true
plots: true
verbose: true
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.3
degrees: 15.0
translate: 0.15
scale: 0.4
shear: 5.0
perspective: 0.0005
fliplr: 0.5
flipud: 0.0
mosaic: 0.0
mixup: 0.6
copy_paste: 0.7
erasing: 0.4
auto_augment: randaugment
