task: obb
mode: train
model: yolo11n-obb.pt
imgsz: 1024
epochs: 150
batch: 8
device: 0
seed: 42
workers: 4
patience: 50
optimizer: auto
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
project: trainning/obb_training_runs
name: obb_run
exist_ok: true
save: true
plots: true
verbose: true
data: C:\Users\floot\Florian's Laptop\ESILV\CV and Deep Learning\ESILV_A5_Computer_Vision\dataset_creation\datasets\label_studio_export_obb_dataset_augmented\data.yaml
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 10.0
translate: 0.1
scale: 0.5
shear: 8.0
perspective: 0.001
fliplr: 0.5
flipud: 0.0
mosaic: 1.0
mixup: 0.1
copy_paste: 0.0
close_mosaic: 10
